
global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "agent_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

